[phases.setup]
nixPkgs = ["python312", "ffmpeg"]

[phases.install]
cmds = [
  "curl -O https://bootstrap.pypa.io/get-pip.py",
  "python3.12 get-pip.py",
  "python3.12 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.12 main.py"
