[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 main.py"
